
		
		<!-- FOOTER -->
		<div id="footer">
			<div id="footer-column-1" class="footer-column">
				<h2>MON ECOLE</h2>
		<a href="http://www.esaip.org/">
			<img src="images/logo-esaip.png">
		</a>
				<p style="text-align:center;font-size:10px;">GROUPE ESAIP</br>18, rue du 8 mai 1945</br>St Barthélemy d'Anjou , 49124</br>info@esaip.org 02 41 96 65 10</p>
			</div>
			<div id="footer-column-2" class="footer-column">
				<h2>MENU PRINCIPAL</h2>
				<?php include "inc/menus/menu_principal.inc";?>
			</div>
					
		</div>
		</section>
	</body>



</html>